blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/smrinalsingh/treeplan/blob/main/README.md
    about: Read the documentation for installation and usage instructions
  - name: Contributing Guidelines
    url: https://github.com/smrinalsingh/treeplan/blob/main/CONTRIBUTING.md
    about: Learn how to contribute to TreePlan
